line-length = 100
extend-exclude = [".venv"]
fix = false
format = "grouped"

select = [
    "ANN",
    "D",
    "E",
    "F",
    "N",
    "W",
]

ignore = [
    "ANN002",
    "ANN003",
    "ANN101",
    "ANN102",
    "ANN204",
    "ANN206",
    "ANN401",
    "D100",
    "D104",
    "D105",
    "D107",
    "D203",
    "D212",
    "D214",
    "D215",
    "D301",
    "D400",
    "D401",
    "D402",
    "D404",
    "D405",
    "D406",
    "D407",
    "D408",
    "D409",
    "D410",
    "D411",
    "D412",
    "D413",
    "D414",
    "D416",
    "D417",
    "N802",
    "N806",
    "N815",
    "N818",
]

[per-file-ignores]
"tests/test_*.py" = [
    "D103",
    "E501",
]

[isort]
known-first-party = [
    "py-template",
    "tests",
]
no-lines-before = ["local-folder"]
order-by-type = false
